### ISSUE TITLE
Logo proposal !

### ISSUE THREAD

**Issue by radudangratian** [sisygoboom/abuse_detection_steemit#1]
Hello! That is my proposal for you project 

![slve](https://user-images.githubusercontent.com/34451833/39098894-301d39a6-467a-11e8-8b54-a0cc5bc3a262.png)

[Gdrive](https://drive.google.com/open?id=16eNXnl2ZVuabuTNiuJiWsGc-SCjfFv0J)

**Comment by sisygoboom** [comment]
Excellent designs, I've added them to the project; thank you very much for your contribution!
